-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'c9bb99f715b88b25' HASH '9186a0805e4433053b3bef0f3684e643dad24ce5be5baa02bce8a128130b216f' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."TB_MOVIE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 30) NOT NULL,
    "COUNT" INTEGER,
    "IMAGE" CHARACTER VARYING(255),
    "SCORE" FLOAT(53),
    "TITLE" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."TB_MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");     
-- 29 +/- SELECT COUNT(*) FROM PUBLIC.TB_MOVIE;               
INSERT INTO "PUBLIC"."TB_MOVIE" VALUES
(1, 2, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg', 4.5, 'The Witcher'),
(2, 3, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg', 3.3, 'Venom: Tempo de Carnificina'),
(3, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg', 0.0, U&'O Espetacular Homem-Aranha 2: A Amea\00e7a de Electro'),
(4, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg', 0.0, 'Matrix Resurrections'),
(5, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cinER0ESG0eJ49kXlExM0MEWGxW.jpg', 0.0, U&'Shang-Chi e a Lenda dos Dez An\00e9is'),
(6, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg', 0.0, 'Django Livre'),
(7, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg', 0.0, 'Titanic'),
(8, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg', 0.0, 'O Lobo de Wall Street'),
(9, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg', 0.0, U&'Aves de Rapina: Arlequina e sua Emancipa\00e7\00e3o Fantabulosa'),
(10, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg', 0.0, U&'Rogue One: Uma Hist\00f3ria Star Wars'),
(11, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uK15I3sGd8AudO9z6J6vi0HH1UU.jpg', 0.0, 'Star Wars: A Guerra dos Clones'),
(12, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/36LnijfQCOC89rCMOhn2OINXROI.jpg', 0.0, U&'Star Wars: Epis\00f3dio I - A Amea\00e7a Fantasma'),
(13, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 0.0, 'Vingadores: Ultimato'),
(14, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg', 0.0, 'Thor'),
(15, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqh5O4KssfJWI62HGAgrjHXbxhD.jpg', 0.0, 'Cisne Negro'),
(16, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg', 0.0, U&'O Sil\00eancio dos Inocentes'),
(17, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', 0.0, 'Clube da Luta'),
(18, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/31VpBgUX5O4Z3dn5ZbX8HLqoXH3.jpg', 0.0, 'Guerra Mundial Z'),
(19, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vcrgU0KaNj5mKUCIQSUdiQwTE9y.jpg', 0.0, U&'Harry Potter e as Rel\00edquias da Morte - Parte 1'),
(20, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lvOLivVeX3DVVcwfVkxKf0R22D8.jpg', 0.0, 'Harry Potter e a Pedra Filosofal'),
(21, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qNdlZgz9yoSJ8f0YxQWfKGPoVV.jpg', 0.0, U&'Alice no Pa\00eds das Maravilhas'),
(22, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg', 0.0, U&'Animais Fant\00e1sticos e Onde Habitam'),
(23, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg', 0.0, 'A Teoria de Tudo'),
(24, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg', 0.0, 'O Livro de Boba Fett'),
(25, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4LrL40XecjGLRpX5I2gzMTUt04l.jpg', 0.0, U&'O \00daltimo Duelo'),
(26, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', 0.0, 'Interestelar'),
(27, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg', 0.0, 'Contato'),
(28, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg', 0.0, 'Duna'),
(29, 0, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2cUsDz4TzFYHrKktT1bKHHQ7Cgm.jpg', 0.0, 'Aquaman');     
CREATE MEMORY TABLE "PUBLIC"."TB_USER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "EMAIL" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."TB_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.TB_USER; 
INSERT INTO "PUBLIC"."TB_USER" VALUES
(1, 'maria@gmail.com'),
(2, 'joao@gmail.com'),
(3, 'ana@gmail.com'),
(4, 'lucia@gmail.com'),
(5, 'joaquim@gmail.com');             
CREATE MEMORY TABLE "PUBLIC"."TB_SCORE"(
    "MOVIE_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "SCORE_VALUE" DECIMAL(10, 2)
);               
ALTER TABLE "PUBLIC"."TB_SCORE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("MOVIE_ID", "USER_ID");    
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.TB_SCORE;
INSERT INTO "PUBLIC"."TB_SCORE" VALUES
(1, 1, 5.00),
(1, 2, 4.00),
(2, 1, 3.00),
(2, 2, 3.00),
(2, 3, 4.00);             
ALTER TABLE "PUBLIC"."TB_SCORE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_60" FOREIGN KEY("MOVIE_ID") REFERENCES "PUBLIC"."TB_MOVIE"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."TB_SCORE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_600" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."TB_USER"("ID") NOCHECK;  
